[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#6739B7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F2FF"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true
